site_name: ''
site_description: AWS Cloud Club
site_url: https://www.awscloudclub.site

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo_round.png
  features:
    - toc.integrate

  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - blog:
      archive: false
      pagination_keep_content: false
      blog_toc: true
      categories_toc: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3  # Adjust this as needed to control the depth of TOC entries
