site_name:  ''
site_description: AWS Cloud Club
site_url: https://www.awscloudclub.site

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo_round.png
  custom_dir: overrides
  features:
    - toc.integrate

plugins:
  - search
  - blog:
      archive: false
      pagination_keep_content: false