site_name:  'AWS Cloud Club'
site_description: AWS Cloud Club
site_url: https://www.awscloudclub.site

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo_round.png
  custom_dir: overrides

plugins:
  - search
  - blog:
      archive_name: Year Publish